# Generated by Django 6.0.3 on 2026-04-05 05:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('project_type', models.CharField(choices=[('cms', 'CMS Website'), ('ecommerce', 'Ecommerce'), ('ai', 'AI Service'), ('custom', 'Custom Development')], max_length=50)),
                ('timeline', models.CharField(choices=[('normal', 'Normal'), ('fast', 'Fast'), ('urgent', 'Urgent')], max_length=20)),
                ('contact_preference', models.CharField(max_length=20)),
                ('rough_price', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Intake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pages', models.IntegerField()),
                ('addons', models.TextField(blank=True)),
                ('content', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.lead')),
            ],
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.FloatField()),
                ('breakdown', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('intake', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.intake')),
            ],
        ),
    ]
