# Generated by Django 6.0.3 on 2026-04-05 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='intake',
            name='ai_package',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='intake',
            name='branding_ready',
            field=models.CharField(default='client', max_length=20),
        ),
        migrations.AddField(
            model_name='intake',
            name='custom_package',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='intake',
            name='ecommerce_platform',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='intake',
            name='integrations',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='intake',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='intake',
            name='timeline_confirm',
            field=models.CharField(default='normal', max_length=20),
        ),
        migrations.AddField(
            model_name='lead',
            name='budget_range',
            field=models.CharField(choices=[('low', 'Below $300'), ('mid', '$300 to $1000'), ('high', 'Above $1000'), ('undecided', 'Undecided')], default='undecided', max_length=20),
        ),
        migrations.AddField(
            model_name='lead',
            name='business_ready',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lead',
            name='client_need',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='lead',
            name='disqualification_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='lead',
            name='expected_benefit',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='lead',
            name='is_decision_maker',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lead',
            name='is_serious',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lead',
            name='needs_human',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lead',
            name='phone',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='lead',
            name='primary_goal',
            field=models.CharField(choices=[('website_presence', 'Website Presence'), ('online_sales', 'Online Sales'), ('automation', 'Automation'), ('branding', 'Branding'), ('social_only', 'Social Media Presence Only')], default='website_presence', max_length=30),
        ),
        migrations.AddField(
            model_name='lead',
            name='recommended_service',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='lead',
            name='source',
            field=models.CharField(choices=[('facebook', 'Facebook'), ('whatsapp', 'WhatsApp'), ('instagram', 'Instagram'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='lead',
            name='stage',
            field=models.CharField(choices=[('new', 'New Lead'), ('qualified', 'Qualified'), ('unqualified', 'Unqualified'), ('proposal_sent', 'Proposal Sent'), ('human_handoff', 'Human Handoff'), ('won', 'Won'), ('lost', 'Lost')], default='new', max_length=30),
        ),
        migrations.AddField(
            model_name='quote',
            name='monthly_cost',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quote',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='quote',
            name='status',
            field=models.CharField(default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='intake',
            name='pages',
            field=models.IntegerField(default=1),
        ),
    ]
