# Generated by Django 6.0.3 on 2026-04-05 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_intake_ai_package_intake_branding_ready_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='lead_score',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
