# Generated by Django 6.0.3 on 2026-04-05 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_lead_lead_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='assets_ready',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lead',
            name='business_name',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='lead',
            name='can_pay_deposit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lead',
            name='current_presence_link',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='lead',
            name='first_message',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='lead',
            name='next_action',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='lead',
            name='seriousness_level',
            field=models.CharField(default='cold', max_length=10),
        ),
        migrations.AddField(
            model_name='lead',
            name='willing_to_call',
            field=models.BooleanField(default=False),
        ),
    ]
