# Generated by Django 6.0.3 on 2026-04-05 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_lead_assets_ready_lead_business_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='client_need_details',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='lead',
            name='content_ready',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lead',
            name='expected_benefit_details',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='lead',
            name='first_message_summary',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='lead',
            name='images_ready',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lead',
            name='logo_ready',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lead',
            name='source_campaign',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='lead',
            name='source_detected_by',
            field=models.CharField(default='auto', max_length=20),
        ),
        migrations.AlterField(
            model_name='lead',
            name='client_need',
            field=models.CharField(default='website_presence', max_length=40),
        ),
        migrations.AlterField(
            model_name='lead',
            name='expected_benefit',
            field=models.CharField(default='increase_sales', max_length=40),
        ),
        migrations.AlterField(
            model_name='lead',
            name='source',
            field=models.CharField(choices=[('facebook', 'Facebook'), ('whatsapp', 'WhatsApp'), ('instagram', 'Instagram'), ('google', 'Google Ads'), ('website', 'Website'), ('referral', 'Referral'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
