# Generated by Django 6.0.3 on 2026-04-05 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_lead_client_need_details_lead_content_ready_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='location',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.CreateModel(
            name='FollowUpTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_offset', models.PositiveSmallIntegerField(default=1)),
                ('due_at', models.DateTimeField()),
                ('status', models.CharField(default='pending', max_length=20)),
                ('message', models.TextField(blank=True, default='')),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.lead')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=40, unique=True)),
                ('subtotal', models.FloatField(default=0)),
                ('discount', models.FloatField(default=0)),
                ('surcharge', models.FloatField(default=0)),
                ('total_amount', models.FloatField(default=0)),
                ('outstanding_balance', models.FloatField(default=0)),
                ('payment_terms', models.CharField(default='Payment due in 7 days', max_length=120)),
                ('due_date', models.DateField()),
                ('status', models.CharField(default='sent', max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('last_reminder_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.lead')),
                ('quote', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.quote')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_type', models.CharField(default='pre_due', max_length=20)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('channel', models.CharField(default='email', max_length=20)),
                ('note', models.TextField(blank=True, default='')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.invoice')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='active', max_length=20)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('expected_delivery', models.DateField(blank=True, null=True)),
                ('is_priority', models.BooleanField(default=False)),
                ('assigned_to', models.CharField(blank=True, default='', max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.invoice')),
                ('lead', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.lead')),
            ],
        ),
        migrations.CreateModel(
            name='CommunicationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(default='whatsapp', max_length=20)),
                ('direction', models.CharField(default='outbound', max_length=10)),
                ('message_type', models.CharField(default='update', max_length=30)),
                ('content', models.TextField()),
                ('status', models.CharField(default='sent', max_length=20)),
                ('response_time_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.lead')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.invoice')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.projectexecution')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('order', models.PositiveSmallIntegerField(default=1)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('eta', models.DateField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('client_update', models.TextField(blank=True, default='')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.projectexecution')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
