# Generated by Django 6.0.3 on 2026-04-05 07:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_lead_location_followuptask_invoice_paymentreminder_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceAddOn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_unit', models.CharField(default='one-time', max_length=30)),
                ('max_quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('icon', models.CharField(blank=True, default='', max_length=50)),
                ('order', models.PositiveSmallIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Service Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='lead',
            name='client_feedback',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='lead',
            name='content_delivery',
            field=models.CharField(blank=True, choices=[('client_provides', 'Client provides content/assets'), ('we_create', 'We create content'), ('mixed', 'Mixed approach')], max_length=50),
        ),
        migrations.AddField(
            model_name='lead',
            name='current_milestone',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='lead',
            name='current_workflow_step',
            field=models.CharField(choices=[('sales', 'Sales/Lead Capture'), ('intake', 'Intake/Requirements'), ('pricing', 'Pricing/Quote'), ('production', 'Production/Execution'), ('invoice', 'Invoice Generated'), ('delivery', 'Delivered/Review'), ('support', 'Support')], default='sales', max_length=50),
        ),
        migrations.AddField(
            model_name='lead',
            name='delivered_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='expected_completion_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='feedback_received_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='human_requested',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lead',
            name='invoice_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='lead',
            name='invoice_sent_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='pages_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='payment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'Unpaid'), ('partial', 'Partial Payment'), ('paid', 'Paid'), ('overdue', 'Overdue')], default='unpaid', max_length=20),
        ),
        migrations.AddField(
            model_name='lead',
            name='priority',
            field=models.CharField(choices=[('normal', 'Normal (7-10 days)'), ('fast', 'Fast (3-5 days)'), ('urgent', 'Urgent (1-2 days)')], default='normal', max_length=20),
        ),
        migrations.AddField(
            model_name='lead',
            name='production_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('on_hold', 'On Hold'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='lead',
            name='project_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='quote_breakdown',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='lead',
            name='quote_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='quote_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='quote_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent to client'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='lead',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='selected_features',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='lead',
            name='service_specific_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='lead',
            name='support_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lead',
            name='support_issues',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='lead',
            name='support_tier',
            field=models.CharField(blank=True, choices=[('basic', 'Basic'), ('standard', 'Standard'), ('advanced', 'Advanced')], max_length=20),
        ),
        migrations.AddField(
            model_name='lead',
            name='selected_addons',
            field=models.ManyToManyField(blank=True, to='core.serviceaddon'),
        ),
        migrations.AddField(
            model_name='serviceaddon',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addons', to='core.servicecategory'),
        ),
        migrations.AddField(
            model_name='lead',
            name='service_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.servicecategory'),
        ),
        migrations.CreateModel(
            name='ServicePackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('platform', models.CharField(blank=True, default='', max_length=50)),
                ('features', models.TextField()),
                ('deliverables', models.TextField(blank=True, default='')),
                ('timeline_days', models.PositiveIntegerField(default=5)),
                ('is_active', models.BooleanField(default=True)),
                ('ordering', models.PositiveSmallIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='core.servicecategory')),
            ],
            options={
                'ordering': ['category', 'ordering', 'name'],
            },
        ),
        migrations.AddField(
            model_name='lead',
            name='selected_package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.servicepackage'),
        ),
    ]
