# Generated by Django 6.0.3 on 2026-04-05 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_serviceaddon_servicecategory_lead_client_feedback_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='contact_block_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lead',
            name='delivery_block_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lead',
            name='processor_phase',
            field=models.CharField(default='LEAD_CAPTURE', max_length=30),
        ),
        migrations.AddField(
            model_name='lead',
            name='qualified_for_handoff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lead',
            name='readiness_percent',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lead',
            name='risk_check_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lead',
            name='risk_flags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='lead',
            name='service_block_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lead',
            name='service_plan',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
