# Generated by Django 6.0.3 on 2026-04-06 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_lead_contact_block_complete_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='csat_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='lead',
            name='csat_helpful',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
