"""
Complete Divi Hosting service catalog with pricing and packages.
This data will be loaded via Django fixture/management command.
"""

DIVI_SERVICES = {
    'cms': {
        'name': '1. CMS Web Development',
        'description': 'Professional website design and development on WordPress, Wix, Squarespace',
        'icon': '🌐',
        'packages': {
            'wordpress_1page': {
                'name': 'WordPress 1-Page',
                'platform': 'WordPress',
                'base_price': 199,
                'features': [
                    'Responsive design',
                    'SEO optimized',
                    'WhatsApp integration',
                    'Video players',
                    'Google Analytics',
                    'Content writing included',
                    'Divi theme license',
                    'Divi Express included',
                ],
                'timeline_days': 5,
            },
            'wordpress_5page': {
                'name': 'WordPress 5-Page',
                'platform': 'WordPress',
                'base_price': 299,
                'features': [
                    'Responsive design',
                    'SEO optimized',
                    'WhatsApp integration',
                    'Video players',
                    'Google Analytics',
                    'Content writing included',
                    'Divi theme license',
                    'Divi Express included',
                ],
                'timeline_days': 10,
            },
            'wix_starter': {
                'name': 'Wix Starter',
                'platform': 'Wix',
                'base_price': 249,
                'features': [
                    'Responsive design',
                    'SEO optimized',
                    'Wix premium features',
                    'Mobile optimized',
                    'SSL included',
                ],
                'timeline_days': 7,
            },
            'squarespace_starter': {
                'name': 'Squarespace Starter',
                'platform': 'Squarespace',
                'base_price': 249,
                'features': [
                    'Template design',
                    'SEO optimized',
                    'Mobile responsive',
                    'Squarespace features included',
                ],
                'timeline_days': 7,
            },
        },
        'addons': {
            'seo_plus': {
                'name': 'SEO Plus Package',
                'description': 'Extra plugins and premium plugins for advanced SEO',
                'price': 100,
                'unit': 'one-time',
            },
            'extra_page': {
                'name': 'Extra Content Page',
                'description': 'Additional page beyond base package',
                'price': 25,
                'unit': 'per-page',
            },
            'language_setup_1page': {
                'name': 'Language Option (1-Page Setup)',
                'description': 'Multi-language support setup for 1-page site',
                'price': 50,
                'unit': 'one-time',
            },
            'language_setup_5page': {
                'name': 'Language Option (5-Page Setup)',
                'description': 'Multi-language support setup for 5-page site',
                'price': 100,
                'unit': 'one-time',
            },
            'extra_language_page': {
                'name': 'Extra Language Page',
                'description': 'Additional translated page (WPML license extra)',
                'price': 10,
                'unit': 'per-page',
            },
            'auto_translate_2lang': {
                'name': 'Auto-Translate (2 Languages)',
                'description': 'Automatic translation without correction (Polylang free, WPML extra)',
                'price': 60,
                'unit': 'one-time',
            },
            'auto_translate_extra': {
                'name': 'Auto-Translate Extra Language',
                'description': 'Additional language for auto-translation',
                'price': 30,
                'unit': 'one-time',
            },
            'advanced_customization': {
                'name': 'Advanced Customization',
                'description': 'Custom CSS/JavaScript modifications',
                'price': 150,
                'unit': 'one-time',
            },
            'ecommerce_addon': {
                'name': 'E-commerce Add-on',
                'description': 'WooCommerce integration for basic shop',
                'price': 200,
                'unit': 'one-time',
            },
            'maintenance_monthly': {
                'name': 'Monthly Maintenance',
                'description': 'Updates, backups, security monitoring',
                'price': 50,
                'unit': 'monthly',
            },
        },
    },
    'ecommerce': {
        'name': '2. Ecommerce Development',
        'description': 'Complete online store setup on WordPress WooCommerce, Magento, Shopify',
        'icon': '🛒',
        'packages': {
            'woocommerce_basic': {
                'name': 'WooCommerce Basic',
                'platform': 'WordPress WooCommerce',
                'base_price': 600,
                'features': [
                    '10+ product pages',
                    '50+ product capacity',
                    'Payment gateway setup',
                    'Inventory management',
                    'Customer accounts',
                    'Basic shipping',
                    'Order notifications',
                ],
                'timeline_days': 10,
            },
            'magento_basic': {
                'name': 'Magento 2 Basic',
                'platform': 'Magento 2',
                'base_price': 1200,
                'features': [
                    'Advanced product catalog',
                    'Multiple payment methods',
                    'Advanced inventory',
                    'Shipping rules',
                    'Customer segments',
                    'Admin customization',
                    'Scalable infrastructure',
                ],
                'timeline_days': 15,
            },
            'shopify_standard': {
                'name': 'Shopify Standard',
                'platform': 'Shopify',
                'base_price': 500,
                'features': [
                    'Unlimited products',
                    'Payment processing',
                    'Automated emails',
                    'Mobile responsive',
                    'SSL certificate',
                    'Shipping integration',
                    '24/7 support',
                ],
                'timeline_days': 5,
            },
            'lightspeed_standard': {
                'name': 'Lightspeed Standard',
                'platform': 'Lightspeed',
                'base_price': 800,
                'features': [
                    'Omnichannel setup',
                    'POS integration',
                    'Inventory sync',
                    'Payment processing',
                    'Mobile ready',
                ],
                'timeline_days': 10,
            },
        },
        'addons': {
            'product_import': {
                'name': 'Product Import Service',
                'description': 'Import existing products from CSV',
                'price': 150,
                'unit': 'one-time',
            },
            'payment_gateways': {
                'name': 'Additional Payment Gateways',
                'description': 'Setup PayPal, Stripe, local payment methods',
                'price': 100,
                'unit': 'one-time',
            },
            'shipping_zones': {
                'name': 'Advanced Shipping Zones',
                'description': 'Complex shipping rules by region/weight',
                'price': 200,
                'unit': 'one-time',
            },
            'email_marketing': {
                'name': 'Email Marketing Integration',
                'description': 'Mailchimp, Klaviyo, or similar setup',
                'price': 100,
                'unit': 'one-time',
            },
            'analytics_setup': {
                'name': 'Advanced Analytics',
                'description': 'Google Analytics 4, conversion tracking setup',
                'price': 150,
                'unit': 'one-time',
            },
            'customer_loyalty': {
                'name': 'Loyalty/Rewards Program',
                'description': 'Points system, referral program',
                'price': 250,
                'unit': 'one-time',
            },
            'seo_ecommerce': {
                'name': 'E-commerce SEO Pro',
                'description': 'Product schema, structured data, SEO optimization',
                'price': 200,
                'unit': 'one-time',
            },
            'subscription_module': {
                'name': 'Subscription/Recurring Billing',
                'description': 'Enable subscriptions and recurring payments',
                'price': 300,
                'unit': 'one-time',
            },
            'api_integration': {
                'name': 'Third-Party API Integration',
                'description': 'Connect ERP, CRM, accounting software',
                'price': 400,
                'unit': 'one-time',
            },
            'ecommerce_support_monthly': {
                'name': 'Monthly Premium Support',
                'description': 'Dedicated support for store operations',
                'price': 100,
                'unit': 'monthly',
            },
        },
    },
    'flutter': {
        'name': '3. Flutter Apps (Android & iOS)',
        'description': 'Native apps for iOS and Android using Flutter framework',
        'icon': '📱',
        'packages': {
            'corporate_app': {
                'name': 'Corporate App',
                'platform': 'Flutter (iOS+Android)',
                'base_price': 2500,
                'features': [
                    'Company info & services',
                    'Push notifications',
                    'In-app messaging',
                    'Contact forms',
                    'News feed',
                    'Basic analytics',
                    'iOS + Android',
                ],
                'timeline_days': 20,
            },
            'salon_booking': {
                'name': 'Salon/Barbershop Booking App',
                'platform': 'Flutter (iOS+Android)',
                'base_price': 3000,
                'features': [
                    'Staff management',
                    'Service catalog',
                    'Booking system',
                    'Payment processing',
                    'Client profiles',
                    'Appointment reminders',
                    'Review system',
                    'iOS + Android',
                ],
                'timeline_days': 25,
            },
            'beauty_parlor': {
                'name': 'Beauty Parlor App',
                'platform': 'Flutter (iOS+Android)',
                'base_price': 3200,
                'features': [
                    'Service booking',
                    'Package deals',
                    'Before/after gallery',
                    'Staff profiles',
                    'Payment processing',
                    'Loyalty rewards',
                    'Social sharing',
                    'iOS + Android',
                ],
                'timeline_days': 25,
            },
        },
        'addons': {
            'push_notifications': {
                'name': 'Advanced Push Notification System',
                'description': 'Segmented, scheduled push campaigns',
                'price': 200,
                'unit': 'one-time',
            },
            'in_app_messaging': {
                'name': 'In-App Messaging/Chat',
                'description': 'Direct customer support chat',
                'price': 300,
                'unit': 'one-time',
            },
            'payment_processing': {
                'name': 'Payment Processing Setup',
                'description': 'Stripe, PayPal, local payment methods',
                'price': 250,
                'unit': 'one-time',
            },
            'analytics_advanced': {
                'name': 'Advanced Analytics & Tracking',
                'description': 'User behavior, funnels, heatmaps',
                'price': 200,
                'unit': 'one-time',
            },
            'social_integration': {
                'name': 'Social Media Integration',
                'description': 'Facebook, Instagram, TikTok sharing',
                'price': 150,
                'unit': 'one-time',
            },
            'backend_api': {
                'name': 'Custom Backend API',
                'description': 'NodeJS/Laravel API for app',
                'price': 800,
                'unit': 'one-time',
            },
            'app_store_submission': {
                'name': 'App Store Submission',
                'description': 'Setup and submission to Apple App Store & Google Play',
                'price': 300,
                'unit': 'one-time',
            },
            'app_maintenance_monthly': {
                'name': 'Monthly App Maintenance',
                'description': 'Updates, bug fixes, OS compatibility',
                'price': 150,
                'unit': 'monthly',
            },
        },
    },
    'custom_web': {
        'name': '4. Custom Web Development',
        'description': 'Custom development with NodeJS, NextJS, Laravel, etc.',
        'icon': '⚙️',
        'packages': {
            'hourly_rate': {
                'name': 'Hourly Development',
                'platform': 'NodeJS/NextJS/Laravel',
                'base_price': 15,
                'features': [
                    'Flexible timeline',
                    'Custom functionality',
                    'Full customization',
                    'Expert developers',
                    'Agile methodology',
                ],
                'timeline_days': 0,  # Variable
            },
            'crm_starter': {
                'name': 'CRM System (Basic)',
                'platform': 'Laravel/NextJS',
                'base_price': 2500,
                'features': [
                    'Lead management',
                    'Contact database',
                    'Email tracking',
                    'Basic reporting',
                    '30 hours development',
                    'Deployment & config',
                ],
                'timeline_days': 15,
            },
            'erp_starter': {
                'name': 'ERP System (Basic)',
                'platform': 'Laravel',
                'base_price': 3500,
                'features': [
                    'Module setup (10-30 hours)',
                    'Inventory tracking',
                    'Order management',
                    'Reporting',
                    'Data migration',
                    'Training included',
                ],
                'timeline_days': 20,
            },
            'custom_saas': {
                'name': 'Custom SaaS Application',
                'platform': 'NextJS/NodeJS',
                'base_price': 5000,
                'features': [
                    'Multi-user platform',
                    'Authentication',
                    'Payment processing',
                    'API design',
                    'Database setup',
                    'Deployment',
                ],
                'timeline_days': 30,
            },
        },
        'addons': {
            'database_design': {
                'name': 'Advanced Database Design',
                'description': 'Complex schema optimization',
                'price': 600,
                'unit': 'one-time',
            },
            'api_development': {
                'name': 'REST/GraphQL API Dev',
                'description': 'Build scalable APIs',
                'price': 50,
                'unit': 'hourly',
            },
            'third_party_integration': {
                'name': 'Third-Party Integration',
                'description': 'Connect to external services/APIs',
                'price': 400,
                'unit': 'one-time',
            },
            'performance_optimization': {
                'name': 'Performance Optimization',
                'description': 'Caching, CDN, database tuning',
                'price': 500,
                'unit': 'one-time',
            },
            'security_audit': {
                'name': 'Security Audit & Hardening',
                'description': 'Penetration testing, security review',
                'price': 800,
                'unit': 'one-time',
            },
            'devops_setup': {
                'name': 'DevOps & CI/CD Setup',
                'description': 'GitHub Actions, Docker, deployment pipeline',
                'price': 700,
                'unit': 'one-time',
            },
            'support_retainer': {
                'name': 'Support Retainer',
                'description': 'Monthly development hours included',
                'price': 200,
                'unit': 'monthly',
            },
        },
    },
    'video': {
        'name': '5. Video Editing',
        'description': 'Professional video production: corporate, whiteboard, explainer, animation',
        'icon': '🎬',
        'packages': {
            'corporate_30s': {
                'name': 'Corporate Video (30s)',
                'platform': 'Video Production',
                'base_price': 100,
                'features': [
                    'Professional filming',
                    '30-second duration',
                    'Basic editing',
                    'Music & effects',
                    '1 revision round',
                ],
                'timeline_days': 7,
            },
            'whiteboard_30s': {
                'name': 'Whiteboard Animation (30s)',
                'platform': 'Animation',
                'base_price': 100,
                'features': [
                    'Whiteboard-style animation',
                    '30-second duration',
                    'Script included',
                    'Voiceover ready',
                    '1 revision',
                ],
                'timeline_days': 7,
            },
            'explainer_30s': {
                'name': 'Explainer Video (30s)',
                'platform': 'Video Production',
                'base_price': 100,
                'features': [
                    'Concept development',
                    'Storyboarding',
                    'Professional animation',
                    '30-second duration',
                    'Sound design',
                ],
                'timeline_days': 10,
            },
            'animation_30s': {
                'name': 'Full Animation (30s)',
                'platform': 'Animation',
                'base_price': 100,
                'features': [
                    'Custom character animation',
                    '30-second duration',
                    'Motion graphics',
                    'Professional effects',
                    'Voiceover included',
                ],
                'timeline_days': 12,
            },
            'spokesperson_30s': {
                'name': 'Spokesperson Video (30s)',
                'platform': 'Video Production',
                'base_price': 100,
                'features': [
                    'Professional talent',
                    'Studio filming',
                    'On-brand delivery',
                    '30-second duration',
                    'Basic editing',
                ],
                'timeline_days': 5,
            },
        },
        'addons': {
            'extra_seconds_15s': {
                'name': 'Extra 15 Seconds',
                'description': 'Add additional 15 seconds to video',
                'price': 25,
                'unit': 'per-15sec',
            },
            'voiceover_professional': {
                'name': 'Professional Voiceover',
                'description': 'Multi-language professional voice talent',
                'price': 100,
                'unit': 'one-time',
            },
            'music_licensing': {
                'name': 'Premium Music Licensing',
                'description': 'Royalty-free or licensed music',
                'price': 50,
                'unit': 'one-time',
            },
            'revision_round': {
                'name': 'Additional Revision Round',
                'description': 'Extra round of revisions',
                'price': 75,
                'unit': 'one-time',
            },
            'stock_footage': {
                'name': 'Premium Stock Footage',
                'description': 'High-quality stock footage integration',
                'price': 100,
                'unit': 'one-time',
            },
            'subtitle_translation': {
                'name': 'Subtitle Translation',
                'description': 'Subtitles in multiple languages',
                'price': 75,
                'unit': 'per-language',
            },
            'animation_characters': {
                'name': 'Custom Character Animation',
                'description': 'Develop custom animated characters',
                'price': 300,
                'unit': 'one-time',
            },
        },
    },
    'graphic_design': {
        'name': '6. Graphic Design',
        'description': 'Logo design, social media graphics, reel generation',
        'icon': '🎨',
        'packages': {
            'logo_ai': {
                'name': 'AI Logo Design',
                'platform': 'AI Design',
                'base_price': 40,
                'features': [
                    'AI-generated logos',
                    'Vectorized format',
                    '3 design options',
                    '1 revision round',
                ],
                'timeline_days': 2,
            },
            'logo_basic': {
                'name': 'Basic Logo Design',
                'platform': 'Graphic Design',
                'base_price': 80,
                'features': [
                    'Professional design',
                    'Vector files',
                    '3 concept variations',
                    '2 revision rounds',
                    'Color variations',
                ],
                'timeline_days': 3,
            },
            'logo_custom': {
                'name': 'Custom Logo Design',
                'platform': 'Graphic Design',
                'base_price': 150,
                'features': [
                    'Unlimited concepts',
                    'Brand guidelines',
                    'Vector + raster files',
                    'Unlimited revisions',
                    'Brand consultation',
                ],
                'timeline_days': 7,
            },
            'social_package_10': {
                'name': 'Social Media Design (10 Images)',
                'platform': 'Graphic Design',
                'base_price': 100,
                'features': [
                    '10 custom designs',
                    'Brand-consistent',
                    'Multiple sizes (Instagram, Facebook)',
                    'Ready to post',
                ],
                'timeline_days': 5,
            },
            'reel_pack_5': {
                'name': 'Reel Pack (5 Reels)',
                'platform': 'Content Creation',
                'base_price': 100,
                'features': [
                    '5 short-form reels',
                    'Trending audio included',
                    'Captions & effects',
                    'Brand consistent',
                ],
                'timeline_days': 7,
            },
        },
        'addons': {
            'social_media_ai': {
                'name': 'Social Media Design AI',
                'description': 'AI-generated social media graphics',
                'price': 5,
                'unit': 'per-image',
            },
            'social_media_custom': {
                'name': 'Custom Social Media Design',
                'description': 'Hand-designed custom graphics',
                'price': 20,
                'unit': 'per-image',
            },
            'reel_ai': {
                'name': 'AI Reel Generation',
                'description': 'AI-generated short-form video reels',
                'price': 5,
                'unit': 'per-reel',
            },
            'reel_custom': {
                'name': 'Custom Reel Design',
                'description': 'Professionally edited custom reels',
                'price': 10,
                'unit': 'per-reel',
            },
            'brand_guidelines': {
                'name': 'Brand Guidelines Document',
                'description': 'Complete brand style guide PDF',
                'price': 200,
                'unit': 'one-time',
            },
            'packaging_design': {
                'name': 'Packaging Design',
                'description': 'Product box, label, wrapper design',
                'price': 250,
                'unit': 'one-time',
            },
            'illustration_custom': {
                'name': 'Custom Illustration',
                'description': 'Hand-drawn or digital illustrated artwork',
                'price': 100,
                'unit': 'per-illustration',
            },
        },
    },
    'social_promotion': {
        'name': '7. Social Promotion',
        'description': 'Social media marketing campaigns and management',
        'icon': '📢',
        'packages': {
            'campaign_1month': {
                'name': 'Social Campaign (1 Month)',
                'platform': 'Social Media',
                'base_price': 75,
                'features': [
                    'Campaign strategy',
                    'Content calendar',
                    'Daily posts',
                    'Hashtag research',
                    'Basic reporting',
                ],
                'timeline_days': 30,
            },
            'campaign_3month': {
                'name': 'Social Campaign (3 Months)',
                'platform': 'Social Media',
                'base_price': 200,
                'features': [
                    'Comprehensive strategy',
                    'Content creation',
                    'Daily posting',
                    'Community management',
                    'Monthly reports',
                    'Engagement tracking',
                ],
                'timeline_days': 90,
            },
        },
        'addons': {
            'influencer_outreach': {
                'name': 'Influencer Outreach',
                'description': 'Connect with relevant influencers',
                'price': 200,
                'unit': 'one-time',
            },
            'ad_management': {
                'name': 'Paid Ad Management',
                'description': 'Facebook/Instagram ads setup and optimization',
                'price': 300,
                'unit': 'one-time',
            },
            'content_creation': {
                'name': 'Content Creation (20 posts)',
                'description': 'Design + copywrite 20 social posts',
                'price': 250,
                'unit': 'one-time',
            },
            'community_management': {
                'name': 'Community Management (Weekly)',
                'description': 'Respond to comments, engage followers',
                'price': 100,
                'unit': 'monthly',
            },
            'analytics_reporting': {
                'name': 'Advanced Analytics Report',
                'description': 'Deep dive analytics and recommendations',
                'price': 150,
                'unit': 'one-time',
            },
        },
    },
    'ai': {
        'name': '8. AI Services',
        'description': 'Custom AI models for chat, document generation, voice',
        'icon': '🤖',
        'packages': {
            'chatbot_web': {
                'name': 'Web Chatbot (Custom Model)',
                'platform': 'Web-based AI',
                'base_price': 150,
                'features': [
                    'Custom trained model',
                    'Website integration',
                    'Multi-language support',
                    'Conversation history',
                    'Analytics dashboard',
                ],
                'timeline_days': 10,
            },
            'chatbot_whatsapp': {
                'name': 'WhatsApp Chatbot (Custom Model)',
                'platform': 'WhatsApp Business API',
                'base_price': 150,
                'features': [
                    'Custom trained model',
                    'WhatsApp integration',
                    'Automated responses',
                    'Multi-language',
                    'Message templates',
                ],
                'timeline_days': 10,
            },
            'chatbot_facebook': {
                'name': 'Facebook Messenger Chatbot',
                'platform': 'Facebook API',
                'base_price': 150,
                'features': [
                    'Custom AI model',
                    'Messenger integration',
                    'Lead qualification',
                    'Multi-language',
                    'Handoff to human',
                ],
                'timeline_days': 10,
            },
            'doc_generation': {
                'name': 'Document Generation AI',
                'platform': 'LLM-based',
                'base_price': 100,
                'features': [
                    'Invoice generation',
                    'Quote generation',
                    'Report generation',
                    'Template-based',
                    'Format options (PDF, docx)',
                ],
                'timeline_days': 7,
            },
        },
        'addons': {
            'training_data': {
                'name': 'Model Fine-Tuning',
                'description': 'Train AI on your specific data/documents',
                'price': 300,
                'unit': 'one-time',
            },
            'voice_integration': {
                'name': 'Voice/Phone Integration',
                'description': 'Inbound phone support with AI voice',
                'price': 400,
                'unit': 'one-time',
            },
            'sentiment_analysis': {
                'name': 'Sentiment Analysis',
                'description': 'Analyze customer sentiment in messages',
                'price': 150,
                'unit': 'one-time',
            },
            'nlp_customization': {
                'name': 'NLP Customization',
                'description': 'Advanced natural language processing',
                'price': 250,
                'unit': 'one-time',
            },
            'multilingual_model': {
                'name': 'Add Language Support',
                'description': 'Support additional language',
                'price': 100,
                'unit': 'per-language',
            },
            'ai_voice_agent': {
                'name': 'AI Voice Agent (Inbound)',
                'description': 'Automated phone answering with AI',
                'price': 500,
                'unit': 'one-time',
            },
            'api_access': {
                'name': 'API Access (Monthly)',
                'description': 'Access to chat API with monthly quota',
                'price': 50,
                'unit': 'monthly',
            },
        },
    },
    'hosting': {
        'name': '9. Hosting',
        'description': 'Shared hosting, VPS, and dedicated servers',
        'icon': '🖥️',
        'packages': {
            'shared_basic': {
                'name': 'Shared Hosting Basic',
                'platform': 'Shared Server',
                'base_price': 5,
                'features': [
                    'Unlimited domains',
                    'Unlimited storage',
                    'Unlimited bandwidth',
                    'Email accounts',
                    'Daily backups',
                ],
                'timeline_days': 0,
            },
            'shared_ecommerce': {
                'name': 'Shared Hosting E-commerce',
                'platform': 'Shared Server',
                'base_price': 7.50,
                'features': [
                    'E-commerce optimized',
                    'SSL certificate',
                    'Better performance',
                    'Database size increased',
                    'Daily backups',
                ],
                'timeline_days': 0,
            },
            'shared_plus': {
                'name': 'Shared Hosting Plus',
                'platform': 'Shared Server',
                'base_price': 15,
                'features': [
                    'Premium support',
                    'Staging environment',
                    'Advanced caching',
                    'Unlimited resources',
                    'DDoS protection',
                ],
                'timeline_days': 0,
            },
            'vps_standard': {
                'name': 'VPS Standard',
                'platform': 'Virtual Private Server',
                'base_price': 30,
                'features': [
                    '2GB RAM',
                    '40GB SSD',
                    '2TB bandwidth',
                    'Root access',
                    '99.9% uptime SLA',
                    'Managed support',
                ],
                'timeline_days': 1,
            },
            'vps_plus': {
                'name': 'VPS Plus',
                'platform': 'Virtual Private Server',
                'base_price': 45,
                'features': [
                    '4GB RAM',
                    '80GB SSD',
                    '4TB bandwidth',
                    'Root access',
                    '99.95% uptime SLA',
                    'Priority support',
                ],
                'timeline_days': 1,
            },
            'dedicated_standard': {
                'name': 'Dedicated Server Standard',
                'platform': 'Dedicated Server',
                'base_price': 75,
                'features': [
                    'Intel Xeon CPU',
                    '16GB RAM',
                    '500GB SSD',
                    'Unlimited bandwidth',
                    'RAID protection',
                    'DDoS protection',
                ],
                'timeline_days': 2,
            },
            'dedicated_plus': {
                'name': 'Dedicated Server Plus',
                'platform': 'Dedicated Server',
                'base_price': 150,
                'features': [
                    'Intel Xeon E5 CPU',
                    '32GB RAM',
                    '1TB SSD',
                    'Unlimited bandwidth',
                    'Managed support 24/7',
                    'Advanced DDoS',
                ],
                'timeline_days': 2,
            },
            'dedicated_pro': {
                'name': 'Dedicated Server Pro',
                'platform': 'Dedicated Server',
                'base_price': 250,
                'features': [
                    'Premium CPU (E5-2680)',
                    '64GB RAM',
                    '2TB NVMe SSD',
                    'Unlimited bandwidth',
                    '24/7 management',
                    'Multi-IP suite',
                ],
                'timeline_days': 2,
            },
            'dedicated_advance': {
                'name': 'Dedicated Server Advance',
                'platform': 'Dedicated Server',
                'base_price': 350,
                'features': [
                    'Top-tier CPU (Platinum)',
                    '128GB RAM',
                    '4TB NVMe SSD RAID-10',
                    'Unlimited bandwidth',
                    'Full management',
                    'High availability setup',
                ],
                'timeline_days': 3,
            },
        },
        'addons': {
            'ssl_certificate': {
                'name': 'SSL Certificate (Wildcard)',
                'description': 'Multi-domain SSL security',
                'price': 50,
                'unit': 'yearly',
            },
            'backup_advanced': {
                'name': 'Advanced Backup (Weekly)',
                'description': 'Weekly off-site backups',
                'price': 20,
                'unit': 'monthly',
            },
            'ddos_protection': {
                'name': 'DDoS Protection',
                'description': 'Advanced DDoS filtering',
                'price': 30,
                'unit': 'monthly',
            },
            'cdn_integration': {
                'name': 'CDN Integration',
                'description': 'Global content delivery network',
                'price': 25,
                'unit': 'monthly',
            },
            'server_migration': {
                'name': 'Server Migration',
                'description': 'Professional migration service',
                'price': 200,
                'unit': 'one-time',
            },
            'monitoring_setup': {
                'name': 'Advanced Monitoring',
                'description': 'Uptime monitoring, alerts, reporting',
                'price': 40,
                'unit': 'monthly',
            },
        },
    },
}
